version: 2.1

parameters:
  build:
    type: boolean
    default: false
  update:
    type: boolean
    default: false

jobs:
  build-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            mkdir test
            cd test
            pwd
            echo 'build' > test.txt
      - run
         name: "test dir"
         command: |
           pwd
           cat test.txt

  update-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo 'update'
  
workflows:
  build-workflow:
    when: << pipeline.parameters.build >>
    jobs:
      - build-job
 
  update-workflow:
    when: << pipeline.parameters.update >>
    jobs:
      - update-job
