version: 2.1

commands:
  test-sh:
    steps:
      - attach_workspace:
          at: ~/
      - run:
        command: |
          cat .circleci/ansible/migstat.txt
          status=$( cat .circleci/ansible/migstat.txt )
          echo $status
          if(( $status -eq 0 ));
          then
            echo Zero
          else
            echo Not Zero
          fi
jobs:
  say-hello:
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - checkout
      - attach_workspace:
            at: ~/
      - run:
          name: "Say hello"
          command: echo '1' > .circleci/migstat.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/migstat.txt
      - test-sh

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
